version: '3.7'
services:
    gui:
        build:
            context: .
        ports: 
            - "${REACT_APP_PORT:-3000}:80"
        container_name: react-d3
        environment:
            - REACT_APP_PORT=${REACT_APP_PORT}